### ISSUE TITLE
how to 1-click upgrade

### ISSUE THREAD

**Issue by BonderTam** [midwayjs/midway-upgrade#7]
npx: the --ignore-existing argument has been removed.
See `npm help exec` for more information
Need to install the following packages:
  midway-upgrade
Ok to proceed? (y) y
The current framework version (koa 3.4) does not support upgrading

**Comment by BonderTam** [comment]
这个项目基本是2022年2月发布就没更新过的， @midwayjs/koa@3.4.7 是2022年6-7月发布的， 这就不能升级了？？

**Comment by czy88840616** [comment]
Same as https://github.com/midwayjs/midway/issues/2519
